### ISSUE TITLE
Add test for same domain

### ISSUE THREAD

**Issue by lenmetson** [CampaignLab/scraping-candidate-websites#6]
Add a test for whether the links are from the candidate's homepage domain so as to avoid crawling external websites.

**Comment by Luciensday** [comment]
Base Domain Check in extract_internal_links function:

##Original Code:
```
if urlparse(base_url).netloc == urlparse(url).netloc and 'search?' not in url:
```

##Modified Code:
```
base_domain = urlparse(base_url).netloc
if urlparse(url).netloc == base_domain and 'search?' not in url:
```
